name: windows-build
on:
  push:
  pull_request:

concurrency:
  group: "windows-build-${{ github.event.pull_request.number }}"
  cancel-in-progress: true

jobs:
  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}
    env:
      BOOST_ROOT: C:\local\boost_1_82_0
    steps:
      - name: Checkout YggdrasilCore
        uses: actions/checkout@v3
        with:
          repository: 'YggdrasilWotLK/yggdrasilcore'
          ref: 'master-shadows'
      - name: Checkout Shadows Module
        uses: actions/checkout@v3
        with:
          repository: 'YggdrasilWotLK/mod-shadows'
          path: 'modules/mod-shadows'
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2.13
      - name: Configure OS
        shell: bash
        env:
          CONTINUOUS_INTEGRATION: true
        run: |
          ./acore.sh install-deps
      - name: Build
        shell: bash
        run: |
          export CTOOLS_BUILD=all
          ./acore.sh compiler build
